### ISSUE TITLE
Goodbye, nameless.

### ISSUE THREAD

**Issue by glitchboyl** [glitchboyl/blog#17]
I will remember you.

Nameless, 为什么是这个名字呢?
不是因为不知道起什么名字所以没有名字, 而是因为 —— **它什么都不是, 所以没有名字.**

它是我说心里话的方式, 是记笔记的方式.
但我不想它只是一个这样的, 玩具. 我希望它能更酷一点.

目前它不支持:
- About、友链等自定义页面.
别人加了我的友链我却没办法加别人的.
- Dark Mode. 
大量的留白让我晚上自己看眼睛都很不舒服.
- 离线缓存. 
如果 GitHub 的接口挂了那我文章就没了.

于是我想着重构它, 那是 Nameless 2.0 ?
不不不, 我不再想它什么都不是了. 它要 是一个很酷的东西.

然后我还想让它更酷:
- 支持从 掘金、SegmentFault、知乎、码云 等平台获取文章的方式 ?
- 支持 SSR、RSS ?
- 插件机制 ?

它会这么酷的话, 那它就好像 Nameless 这颗小星球的万古长夜里终于迎来了天明.
它会被我称作 **朝**, 日文里读作 **Asa**. 也是因为我最近听的[这首歌](https://music.163.com/#/song?id=1451700517)实在是太好听了.

那么, 就此告别了... Nameless.

---
这是我对 Nameless 的告别文, 但不是最后一篇文章, 并且我会在它在发出去之后 close 目前所有的文章.
All past is over, 人生翻篇重新开始一点点积累.

最后在这篇文章的最后, 我就简单做个年中人生总结吧.

今年是 2020 年, 开了个非常不好的头. 
疫情在世界蔓延的非常严重, 但万幸的是, 它没有伤害到我身边的、我所认识的亲爱的亲人朋友们.

我还是如同往常一样 浑浑噩噩, 逃避现实.
虽然一直在自嘲, 但有时候还是不想承认自己的失败和无能, 连朋友都所剩无几.
最近更频繁的在思考生的意义了, 总觉得自己平日里做的都是无意义的事情.
实际上我会不会只是一个 **"缸中之脑"** ? 细思极恐.

不, 我想避免这样的想法. 为此, 要从改变生活方式、日常习惯开始.
接下来我要进行一些系统性的学习: 学习英语、学习算法、学习理财、学习如何让自己和周围的人开心.
让自己的知识能够帮助别人. 打入技术圈, 认识一些圈里的带佬.

如果永之长眠是如愿以偿, 那可以在这之前做点有意义的事情, 然后在这之后做个好梦.

![](https://i.loli.net/2020/07/28/Oy3WpKJziLn1qBg.png)

很希望我能做到.

**Comment by yuxino** [comment]
![2557ZPgAl](https://user-images.githubusercontent.com/12481935/88746086-3eec9d00-d17e-11ea-9146-475a90323d29.gif)

繰り返す日々まで あなたにも見せたくて 

泪の目，さようなら，Nameless

**Comment by glitchboyl** [comment]
@yuxino 生不出人, 我很抱歉. :dog:
