### ISSUE TITLE
用 Typescript 重写了 Nameless

### ISSUE THREAD

**Issue by glitchboyl** [glitchboyl/blog#5]
这里是我这段时间学习 Typescript,
以及使用它重写了 Nameless 所踩的一些坑的综合总结.

如果你还不知道 Typescript (以下简称为 TS) 是什么, 请戳[这里](https://www.tslang.cn/).
~如果你还不知道 Nameless 是什么, 请戳[这里](https://github.com/LonelyLiaR/Nameless/). 🐶~

## 为什么要学习 TS?
TS 发展的越来越快, 生态圈也越来越好. 
一些大型项目开始逐渐使用 TS. 其提供的静态类型系统, 大大增强了代码的可读性以及可维护性.

所以我也打算顺着潮流, 学习一下 TS, 扩展技能槽.

## 为什么要重写 Nameless?
之前的 Nameless 在我看来源码的可读性以及可维护性都太差了.  ![weak b](https://i.loli.net/2019/03/26/5c99f3c07c3be.jpg)
所以作为学习 TS 的练手项目, 顺便提高一下代码质量. ~可能现在更差了. txtx~

## 开始学习 TS
TS 的教程文档网上遍地都是, 最好的当然还是[官方文档](https://www.typescriptlang.org/docs/).
一开始看起来真的会很有压力的话, 可以选择去看一些其他人撰写的教程文档来入门.
我选择看的是 [xcatliu 的 TS 教程](https://ts.xcatliu.com). 里面讲的还是比较通俗易懂的.

入门完之后我对于 TS 的理解:
TS 主要的两个特点就是 **静态类型系统** 以及 **对ES6/7的支持**.

首先静态类型带来的好处就是, 代码变得更好看/规范了. 
几乎所有的变量都需要定义类型, 并且在与方法/接口等交互时都很严格的按照定义的类型来.
配合 IDE 还会提示报错, 在编写代码和编译阶段就能发现大量错误.
或者提示代码, 可以跳转到定义直接查看. 大大提高了开发生产力.

TS 对 ES6/7 的支持使得可以直接在 TS 里写 ES6/7 的代码.
编译出来的 Javascript 可以运行在任何浏览器上, 兼容性也无问题.

## 将 TS 运用到项目里
Nameless 是基于 [React](https://reactjs.org/) 开发的, 所以我用 [CRA](https://facebook.github.io/create-react-app/) 重新创建了一个 TS 项目.
```shell
$ yarn create react-app nameless --typescript
```
肉眼可见的区别就是在根目录多了一个 `tsconfig.json`.

接下来将 Nameless 的全部文件移进去, 重命名为 TS 文件.
例如 `src/index.js` 重命名为 `src/index.ts`, 如果为 `.jsx` 文件则要重命名为 `.tsx`.
启动开发服务器, 然后 不出意料的 报错了...

第一个遇到的**错误**就是 _Could not find a declaration file for module '...'_ .
在 TS 里, 所有第三方库都会有一个声明文件, 用于为编辑器获得对应的**代码补全**、**接口提示**等功能.
由 `@types` 统一管理. 使用方法很简单, 直接安装对应的声明模块即可, 

以 styled-components 举例:
```shell
$ npm install @types/styled-components
# or use yarn
$ yarn add @types/styled-components
```
安装完所有第三方库的声明模块后, 再次启动开发服务器.

再次**报错**... 这次报的错误是 _Parameter '...' implicitly has an 'any' type_ .
这其实不是个错误, 只是个警告. 
在 TS 里, 如果没有为变量指定类型, 那它就会依照类型推论的规则推断出一个类型. 例如:
```typescript
let boy = 'next door';
```
它实际上等价于:
```typescript
let boy: string = 'next door';
```
你不能把它赋值给其它类型, 如果这样做会报警告.
如果定义变量的时候没有赋值, 不管之后有没有赋值, 都会被推断成 `any` 类型而完全不被类型检查:
```typescript
function boy (next) {  
/* 相当于 
function boy (next: any) {
*/
  return next.door;
}
// 假如传入的 next 是 string 类型的参数. 函数无返回值, 毫无意义了.
boy('易建联'); // `undefined`
```
TS 在编译期就察觉到这个隐式错误, 直接抛出警告.  解决方法有二:
1) ~老老实实~ 为变量指定类型. 即便是 `any` 类型都可以.
2) 打开根目录下的 `tsconfig.json`, 在 `"compilerOptions"` 里加入 `"noImplicitAny": false`; 或者将 `"strict"` 的值改为 `false` 关闭严格模式, 让它们不会对这种隐式错误抛出警告. 
当然以这种方法解决的话那么引入 TS 就毫无意义了.

先暂时把函数参数变量指定为 `any` 类型让它通过 TS 编译.
遇到了第三个**错误**: _Cannot find module 'config'_ .

`config` 在 `src` 文件夹下, 是一个 `json` 类型的文件, 用于 Nameless 的一些基础配置定义. 
能够直接以绝对路径引用它的原因是我在根目录的 `.env` 文件中设置了 `NODE_PATH=src`.
但是看来在 TS 项目中好像没起到作用. 

在查询了[官方文档](https://www.typescriptlang.org/docs/handbook/module-resolution.html#relative-vs-non-relative-module-imports)后得知: 
> if the module name is non-relative (and in the case of "moduleA", it is), then the compiler will attempt to locate an ambient module declaration.
> 
> You should use relative imports for your own modules that are guaranteed to maintain their relative location at runtime.
> 
> A non-relative import can be resolved relative to baseUrl, or through path mapping.

大概意思就是说:
> 如果模块名是非相对导入的, 编译器会尝试定位一个外部模块声明.
> 
> 自己写的模块使用相对导入(比较好), 这样能确保它们在运行时的相对位置.
> 
> (如果想以)非相对导入(模块)可以相对于 baseUrl 或通过 路径映射 来进行解析.

那么解决方案就是需要用到路径映射, 参照[官方文档的这节](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping), 
在 `tsconfig.json` 里的 `"compilerOptions"` 写入 `"baseUrl"` 和 `"paths"`:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "config": ["src/config.json"]
    }
  }
}
```
保存, 重新启动开发服务器. 依旧还是报了这个错误.
![confuse](https://i.loli.net/2019/12/05/4rTY2IoDVkK5LeQ.png) 这是为啥啊? 难道没起作用?

打开 shell 查看有没有有用的报错信息, 可以看到

![shell](https://i.loli.net/2019/03/26/5c99d928b6f41.png)

看起来好像是 react-scripts 的问题, 查询到[这个issue](https://github.com/facebook/create-react-app/issues/5645)里也有人遇到了和我一样的问题. 
根据[这位大哥提供的解决方案](https://github.com/facebook/create-react-app/issues/5645#issuecomment-435201019)试一下, 创建一个 `tsconfig.paths.json`, 写入:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "config": ["src/config.json"]
    }
  }
}
```
然后在 `tsconfig.json` 里加入: 
```json
{
  "extends": "./tsconfig.paths.json"
}
```
保存, 重新启动开发服务器. 
可以看到 shell 依然会报和上面那个图片里一样的信息, 但是绝对路径引用的 `config` 不再报错了.
之后把用绝对路径引用的 `api/*`、`components/*`、`store/*` 之类的也加入到路径映射.

接下来到每个文件里去为变量指定类型. 如果是 `JSONObject` 类型的参数就定义一个 [interface](https://ts.xcatliu.com/basics/type-of-object-interfaces.html). 
不得不说配合 VSCode 真的很爽, 只要有不能通过 TS 编译的地方, 就会被红色下划波浪线标识出来, 告诉你这块不规范, 无法通过编译.

在改的过程中遇到了一个坑, 具体表现是用 [styled-components](https://www.styled-components.com/) 定义的组件嵌套子组件时, 无法通过 TS 编译:

![navbar.tsx](https://i.loli.net/2019/03/26/5c99e84511630.png)

写 interface 是行不通的, 但是有另外一种办法, 那就是使用 [ES6 中的 class(类)](https://ts.xcatliu.com/advanced/class.html).
改写一下 Navbar.tsx:
```tsx
import React from 'react';
import Styled from 'styled-components';

const Navbar = Styled.ul`
    // ...component styles
`;

export default class extends React.Component {
  public static NavItem = Styled.li`
     // ...component styles 
    `
  public render() {
    return <Navbar {...this.props} />;
  }
}
```
这样就可以通过 TS 的编译, 像以前那样调用嵌套的子组件了.
```jsx
<Navbar>
  <Navbar.NavItem></Navbar.NavItem>
</Navbar>
```

## 结语
那么就到这里. [具体的重写](https://github.com/LonelyLiaR/nameless/commit/c9db97bd82bb4c1377556bedced2de0cf295793f)过程其实肯定远远不止这么简单.
这次重写下来, 代码质量和可读性确实比以前好上不少. (自我感觉) 😄

关于 TS 要学的东西还有很多.
越来越感觉自己真的很🥦🐔了, 还是希望读过这个文章的大神们能多多指导.
![cat crying](https://i.loli.net/2019/03/26/5c99f68c3b6c3.gif) ~真的会有人读吗..?~

## 参考资料
https://ts.xcatliu.com/
http://www.17educations.com/parameter-implicitly-type/
https://www.typescriptlang.org/docs/handbook/module-resolution.html
http://www.independent-software.com/styled-components-typescript-dot-notation.html

**Comment by spacemeowx2** [comment]
已阅

**Comment by glitchboyl** [comment]
@spacemeowx2 thks for reading. :grinning:
